### ISSUE TITLE
Please input the best K value：？

### ISSUE THREAD

**Issue by zhangtao22** [wblgers/py_speech_seg#1]
请问这个k value值是如何确定的呢？

**Comment by wblgers** [comment]
请参考“肘部法则”(Elbow Method)来确定KMeans聚类的K值确定，最优的K值点是代价函数的值下降最快的那个点。在py_speech_seg这个例子图示中，可以看到从K=1变化至K=2，均方误差值下降最快，K=2之后则下降比较平缓，因此将K值确定为2。

**Comment by wblgers** [comment]
You can close the issue if these comments are helpful to you.

**Comment by zhangtao22** [comment]
如果我有很多二人对话的语音文件需要分割，难道只能通过眼睛观察elbow嘛？请问这种情况有没有比较通用的方法，谢谢

**Comment by wblgers** [comment]
你可以写一个简单的函数来处理中这个问题，将不同K值对应的模型的均方误差值存放到一个数组，求前后的差值，然后找到差值最大的那个下标，应该就好了吧。

**Comment by wblgers** [comment]
QQ: 649727338
