### ISSUE TITLE
如果录音中有音乐可以切除吗

### ISSUE THREAD

**Issue by heyayun18188** [wblgers/py_speech_seg#10]
如果一段电话录音中有一段铃声，可以自动识别并切除掉吗?
还有就是您的模型的在说话人分离的准确率上表现的怎么样呢?有统计过相应的指标吗?
谢谢!

**Comment by wblgers** [comment]
1. 没试过铃声的切除，你可以试一下，如果BIC的效果不好，你可以选择用神经网络的方式来建模；
2. 没有在标准集上评估说话人分离的准确率，BiLSTM的效果应该还不错，你可以试下
