### ISSUE TITLE
Why the BIC is the trace of convariance matrix instead of the determinant as the paper or your blog said?

### ISSUE THREAD

**Issue by eezprince** [wblgers/py_speech_seg#11]
为什么BIC的公式被改为了协方差矩阵的迹了？你博客里写的是行列式呢？

**Comment by wblgers** [comment]
并不是求得迹，迹是矩阵得特征值之和，我求的是特征值的乘积。
如果一个矩阵有N个不重根的特征值，**那么矩阵的行列式等于所有特征值的乘积**。即：
det0 = max(np.prod(np.maximum(sigma0, eps)), realmin)
这里应该是用的近似算法。如果你想要计算协方差矩阵的行列之，也可以直接用下面的方式：
conv_all = np.cov(mfccs)
log_lh_all = np.log(np.linalg.det(conv_all))
这部分代码在我的博客里有讲到。
