### ISSUE TITLE
Windows python3.8 环境下运行错误

### ISSUE THREAD

**Issue by deiphi** [wblgers/py_speech_seg#12]
你好，我在Windows python3.8 环境下运行错误，能不能帮我看看是什么问题，截图：

![py20200311112136](https://user-images.githubusercontent.com/3659715/76379345-ccc01b00-638a-11ea-8400-1898cefa048d.png)

**Comment by wblgers** [comment]
你的sklearn没有安装好，检查一下sklearn, numpy, scipy是否安装好，缺失的补安装一下。

**Comment by deiphi** [comment]
你好，sklearn 已经安装了，其他库也安装了，但是似乎没有 __check_build 这个文件/模块。
![py_20200311120111](https://user-images.githubusercontent.com/3659715/76381319-1101ea00-6390-11ea-9269-90b64d286e1f.png)

**Comment by wblgers** [comment]
不清楚了，一般来说，用anaconda配置环境，它里面会自带sklearn，scipy和nunpy，并保证不同包之间的兼容性。

**Comment by deiphi** [comment]
好的，谢谢啊~

**Comment by wblgers** [comment]
我目前在win10上测试通过，几个关键的包版本：
scikit-learn              0.19.1
numpy                     1.14.3
scipy                     1.1.0
librosa                   0.6.3
python                  3.6.5

供你参考

**Comment by deiphi** [comment]
好的，非常感谢：）
