### ISSUE TITLE
这个为什么要乘以0.5，公式上并没有乘

### ISSUE THREAD

**Issue by feifaxiaoming** [wblgers/py_speech_seg#6]
BIC = 0.5*(n*np.log(det0)-index*np.log(det1)-(n-index)*np.log(det2))-0.5*(m+0.5*m*(m+1))*np.log(n)

就是最前面的那个0.5，我看您给的公式中并不需要乘以这个0.5

**Comment by wblgers** [comment]
是的，原始的论文中是没有0.5，代码这里加0.5可以等价看做最后一项的正则项为2，是我根据不同的正则项值分别做实验，然后调整确定的。
