### ISSUE TITLE
能提供一下训练的音频格式吗

### ISSUE THREAD

**Issue by zhaowenzi** [wblgers/py_speech_seg#8]
您好，我已经看了prepare_dataset这份代码，但是能提供一下示例的训练音频数据的格式吗  谢谢

**Comment by wblgers** [comment]
已经更新了BiLSTM中的README，你可以在那里找到需要的信息。

**Comment by zhaowenzi** [comment]
> 已经更新了BiLSTM中的README，你可以在那里找到需要的信息。

您好，我已经找到了复现实验相关的音频，但是在您提供的两个下载的地方都没有找到他们的标注文件（也就是all.mdtm这个文件），您能提供一下这个文件的地址吗

**Comment by wblgers** [comment]
> > 已经更新了BiLSTM中的README，你可以在那里找到需要的信息。
> 
> 您好，我已经找到了复现实验相关的音频，但是在您提供的两个下载的地方都没有找到他们的标注文件（也就是all.mdtm这个文件），您能提供一下这个文件的地址吗

https://github.com/pyannote/pyannote-db-odessa-ami/tree/master/AMI/data/speaker_diarization
